version: '3'

services:
  clickhouse_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
    networks:
        - clickhouse_net

  clickhouse_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
        - clickhouse_net

networks:
  clickhouse_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24
